// source: https://github.com/openapi-ts/openapi-typescript/blob/12f9c29b7653db3ab5d6beb4ac698ce5b58177aa/packages/openapi-typescript/src/index.ts#L63
// edit: add onSchemaCreated parameter.
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/ban-ts-comment */
import { performance } from 'node:perf_hooks';
import type { Readable } from 'node:stream';
import { createConfig } from '@redocly/openapi-core';
import type ts from 'typescript';
import { validateAndBundle } from '../../node_modules/openapi-typescript/src/lib/redoc.js';
import {
  debug,
  resolveRef,
  scanDiscriminators,
} from '../../node_modules/openapi-typescript/src/lib/utils.js';
import transformSchema from '../../node_modules/openapi-typescript/src/transform/index.js';
import type {
  GlobalContext,
  OpenAPI3,
  OpenAPITSOptions,
} from '../../node_modules/openapi-typescript/src/types.js';

export * from '../../node_modules/openapi-typescript/src/lib/ts.js';
export * from '../../node_modules/openapi-typescript/src/lib/utils.js';
export { default as transformComponentsObject } from '../../node_modules/openapi-typescript/src/transform/components-object.js';
export { default as transformHeaderObject } from '../../node_modules/openapi-typescript/src/transform/header-object.js';
export { default as transformSchema } from '../../node_modules/openapi-typescript/src/transform/index.js';
export { default as transformMediaTypeObject } from '../../node_modules/openapi-typescript/src/transform/media-type-object.js';
export * from '../../node_modules/openapi-typescript/src/transform/operation-object.js';
export { default as transformOperationObject } from '../../node_modules/openapi-typescript/src/transform/operation-object.js';
export { default as transformParameterObject } from '../../node_modules/openapi-typescript/src/transform/parameter-object.js';
export * from '../../node_modules/openapi-typescript/src/transform/path-item-object.js';
export { default as transformPathItemObject } from '../../node_modules/openapi-typescript/src/transform/path-item-object.js';
export { default as transformPathsObject } from '../../node_modules/openapi-typescript/src/transform/paths-object.js';
export { default as transformRequestBodyObject } from '../../node_modules/openapi-typescript/src/transform/request-body-object.js';
export { default as transformResponseObject } from '../../node_modules/openapi-typescript/src/transform/response-object.js';
export { default as transformResponsesObject } from '../../node_modules/openapi-typescript/src/transform/responses-object.js';
export * from '../../node_modules/openapi-typescript/src/transform/schema-object.js';
export { default as transformSchemaObject } from '../../node_modules/openapi-typescript/src/transform/schema-object.js';
export * from '../../node_modules/openapi-typescript/src/types.js';

export const COMMENT_HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

/**
 * Convert an OpenAPI schema to TypesScript AST
 * @param {string|URL|object|Readable} source OpenAPI schema source:
 *   - YAML: string
 *   - JSON: parsed object
 *   - URL: URL to a YAML or JSON file (local or remote)
 *   - Readable: Readable stream of YAML or JSON
 */
export default async function openapiTS(
  source: string | URL | OpenAPI3 | Buffer | Readable,
  options: OpenAPITSOptions = {} as Partial<OpenAPITSOptions>,
  onSchemaCreated?: (schema: OpenAPI3) => void,
): Promise<ts.Node[]> {
  if (!source) {
    throw new Error(
      'Empty schema. Please specify a URL, file path, or Redocly Config',
    );
  }

  const redoc =
    options.redocly ??
    (await createConfig(
      {
        rules: {
          'operation-operationId-unique': { severity: 'error' }, // throw error on duplicate operationIDs
        },
      },
      { extends: ['minimal'] },
    ));

  const schema = await validateAndBundle(source, {
    redoc,
    cwd:
      options.cwd instanceof URL
        ? options.cwd
        : new URL(`file://${options.cwd ?? process.cwd()}/`),
    silent: options.silent ?? false,
  });

  onSchemaCreated?.(schema);

  const ctx: GlobalContext = {
    additionalProperties: options.additionalProperties ?? false,
    alphabetize: options.alphabetize ?? false,
    arrayLength: options.arrayLength ?? false,
    defaultNonNullable: options.defaultNonNullable ?? true,
    discriminators: scanDiscriminators(schema, options),
    emptyObjectsUnknown: options.emptyObjectsUnknown ?? false,
    enum: options.enum ?? false,
    enumValues: options.enumValues ?? false,
    dedupeEnums: options.dedupeEnums ?? false,
    excludeDeprecated: options.excludeDeprecated ?? false,
    exportType: options.exportType ?? false,
    immutable: options.immutable ?? false,
    rootTypes: options.rootTypes ?? false,
    rootTypesNoSchemaPrefix: options.rootTypesNoSchemaPrefix ?? false,
    injectFooter: [],
    pathParamsAsTypes: options.pathParamsAsTypes ?? false,
    postTransform:
      typeof options.postTransform === 'function'
        ? options.postTransform
        : undefined,
    propertiesRequiredByDefault: options.propertiesRequiredByDefault ?? false,
    redoc,
    silent: options.silent ?? false,
    inject: options.inject ?? undefined,
    transform:
      typeof options.transform === 'function' ? options.transform : undefined,
    // @ts-expect-error
    transformProperty:
      // @ts-expect-error
      typeof options.transformProperty === 'function'
        ? // @ts-expect-error
          options.transformProperty
        : undefined,
    makePathsEnum: options.makePathsEnum ?? false,
    generatePathParams: options.generatePathParams ?? false,
    resolve($ref) {
      return resolveRef(schema, $ref, { silent: options.silent ?? false });
    },
  };

  const transformT = performance.now();
  const result = transformSchema(schema, ctx);
  debug(
    'Completed AST transformation for entire document',
    'ts',
    performance.now() - transformT,
  );

  return result;
}
